# Generated by Django 3.0.5 on 2020-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cat',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cat',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cat',
            name='imageURL',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
